// <auto-generated />
using System;
using Azure.Starter.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Azure.Starter.Database.Migrations
{
    [DbContext(typeof(SampleAppContext))]
    [Migration("20190508153119_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Azure.Starter.Core.Models.SampleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Features");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Samples");

                    b.HasData(
                        new
                        {
                            Id = new Guid("307fe9c6-fb15-4e3e-a3d3-494339348380"),
                            Created = new DateTime(2019, 5, 8, 18, 31, 19, 52, DateTimeKind.Local).AddTicks(2555),
                            Description = "[Description]",
                            DisplayName = "[DisplayName]",
                            Features = "Feature #1,Feature #2,Feature #3",
                            LastUpdated = new DateTime(2019, 5, 8, 18, 31, 19, 52, DateTimeKind.Local).AddTicks(3023),
                            Name = "[Name]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
